-- MySQL Script generated by MySQL Workbench
-- 12/02/15 04:49:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `company` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `company` ;

-- -----------------------------------------------------
-- Table `company`.`Otdel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`Otdel` (
  `idOtdel` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Otdel_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idOtdel`)  COMMENT '',
  INDEX `o1` (`idOtdel` ASC, `Otdel_name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`.`Sotrud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company`.`Sotrud` (
  `idSotrud` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `FIO` VARCHAR(45) NOT NULL COMMENT '',
  `id_Otdel` INT NOT NULL COMMENT '',
  `id_boss` INT NULL COMMENT '',
  `bossname` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idSotrud`)  COMMENT '',
  INDEX `o_idx` (`id_Otdel` ASC)  COMMENT '',
  INDEX `b_idx` (`id_boss` ASC, `bossname` ASC)  COMMENT '',
  INDEX `n` (`idSotrud` ASC, `FIO` ASC, `bossname` ASC)  COMMENT '',
  CONSTRAINT `o`
    FOREIGN KEY (`id_Otdel`)
    REFERENCES `company`.`Otdel` (`idOtdel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `b`
    FOREIGN KEY (`id_boss` , `bossname`)
    REFERENCES `company`.`Sotrud` (`idSotrud` , `FIO`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `company`.`Otdel`
-- -----------------------------------------------------
START TRANSACTION;
USE `company`;
INSERT INTO `company`.`Otdel` (`idOtdel`, `Otdel_name`) VALUES (1, 'Program');
INSERT INTO `company`.`Otdel` (`idOtdel`, `Otdel_name`) VALUES (DEFAULT, 'Analytics');
INSERT INTO `company`.`Otdel` (`idOtdel`, `Otdel_name`) VALUES (DEFAULT, 'financial');

COMMIT;


-- -----------------------------------------------------
-- Data for table `company`.`Sotrud`
-- -----------------------------------------------------
START TRANSACTION;
USE `company`;
INSERT INTO `company`.`Sotrud` (`idSotrud`, `FIO`, `id_Otdel`, `id_boss`, `bossname`) VALUES (1, 'Zabava', 1, NULL, NULL);
INSERT INTO `company`.`Sotrud` (`idSotrud`, `FIO`, `id_Otdel`, `id_boss`, `bossname`) VALUES (DEFAULT, 'Izotov', 1, 1, 'Zabava');
INSERT INTO `company`.`Sotrud` (`idSotrud`, `FIO`, `id_Otdel`, `id_boss`, `bossname`) VALUES (DEFAULT, 'Godunov', 1, 1, 'Zabava');
INSERT INTO `company`.`Sotrud` (`idSotrud`, `FIO`, `id_Otdel`, `id_boss`, `bossname`) VALUES (DEFAULT, 'Karimov', 1, 2, 'Izotov');
INSERT INTO `company`.`Sotrud` (`idSotrud`, `FIO`, `id_Otdel`, `id_boss`, `bossname`) VALUES (DEFAULT, 'Belov', 1, 3, 'Godunov');
INSERT INTO `company`.`Sotrud` (`idSotrud`, `FIO`, `id_Otdel`, `id_boss`, `bossname`) VALUES (DEFAULT, 'nana', 3, NULL, NULL);
INSERT INTO `company`.`Sotrud` (`idSotrud`, `FIO`, `id_Otdel`, `id_boss`, `bossname`) VALUES (DEFAULT, 'kato', 2, NULL, NULL);
INSERT INTO `company`.`Sotrud` (`idSotrud`, `FIO`, `id_Otdel`, `id_boss`, `bossname`) VALUES (DEFAULT, 'Arkadyeva', 2, 7, 'kato');

COMMIT;

